language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - cd $TRAVIS_BUILD_DIR/udagram-users
  - docker build -t "$DOCKER_USERNAME"/udagram-users:latest
  - cd $TRAVIS_BUILD_DIR/udagram-feed
  - docker build -t "$DOCKER_USERNAME"/udagram-feed:latest
  - cd $TRAVIS_BUILD_DIR/udagram-frontend
  - docker build -t "$DOCKER_USERNAME"/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u dmahely --password-stdin
  - docker push "$DOCKER_USERNAME"/udagram-users:latest
  - docker push "$DOCKER_USERNAME"/udagram-feed:latest
  - docker push "$DOCKER_USERNAME"/udagram-frontend:latest
